[workspace]
resolver = "2"
members = [
  "contracts/growthip-creator-registry",
  "contracts/poseidon2",
  "contracts/zk-types",
  "contracts/verifier-v5",
  "contracts/pool-v5"
]

[workspace.dependencies]
soroban-sdk = { version = "26.0.1", features = ["hazmat-crypto"] }

[profile.release]
overflow-checks = true
