[workspace]
resolver = "2"
members = [
  "contracts/square-verifier",
  "contracts/growthip-note-verifier",
  "contracts/growthip-merkle-verifier",
  "contracts/growthip-merkle-verifier-v2",
  "contracts/growthip-merkle-verifier-v3",
  "contracts/growthip-pool",
  "contracts/growthip-merkle-verifier-v3-1",
  "contracts/growthip-creator-registry",
  "contracts/growthip-merkle-verifier-v4",
  "contracts/poseidon2",
  "contracts/zk-types",
  "contracts/verifier-v5",
  "contracts/pool-v5"
]

[workspace.dependencies]
soroban-sdk = { version = "26.0.1", features = ["hazmat-crypto"] }

[profile.release]
overflow-checks = true
