[package]
name = "growthip-pool"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true, features = ["hazmat-crypto"] }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils", "hazmat-crypto"] }
hex = "0.4"
growthip-merkle-verifier-v3 = { path = "../growthip-merkle-verifier-v3" }
growthip-merkle-verifier-v3-1 = { path = "../growthip-merkle-verifier-v3-1" }
growthip-merkle-verifier-v2 = { path = "../growthip-merkle-verifier-v2" }
